; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200

; Required for your N16R8 variant
board_build.flash_size = 16MB
board_build.psram = enabled

; Fix USB serial (VERY important for S3)
build_flags = 
    -DARDUINO_USB_CDC_ON_BOOT=1

lib_deps = 
    fastled/FastLED
    plerup/EspSoftwareSerial@^8.2.0